### ISSUE TITLE
HTTP Request FAILED

### ISSUE THREAD

**Issue by TonyTang2001** [windeaves/Web_Server#5]
During the registration(user signing up) process, HTTP connection was lost when the iOS client's **2nd request** happens, after successfully retrieving salt in the 1st request.

The iOS client is using [Alamofire](https://github.com/Alamofire/Alamofire) to make HTTP request, and has set "App Transport Security Settings"/"Allow Arbitrary Loads" to YES to allow HTTP request.

A sample url for the second request: 
http://xx.xxx.xx.xxx:xxxxx/api/regs?tel=15071001280&mail=398102832@qq.co&passsalt=59f3062cc5295e1de637d93655067e3f

Error info:
2019-01-28 00:01:25.064237+0800 iOS_Client190109[7227:1620179] Task <1F40A198-1728-4979-B7D6-4B58EBFC468B>.<2> HTTP load failed (error code: -1005 [4:-4])
2019-01-28 00:01:25.064738+0800 iOS_Client190109[7227:1619986] Task <1F40A198-1728-4979-B7D6-4B58EBFC468B>.<2> finished with error - code: -1005
2019-01-28 00:01:25.082204+0800 iOS_Client190109[7227:1619986] Task <1F40A198-1728-4979-B7D6-4B58EBFC468B>.<2> load failed with error Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=-4, NSUnderlyingError=0x280adb690 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x28277d540 [0x1c4949610]>{length = 16, capacity = 16, bytes = 0x10025b2527685ae60000000000000000}, _kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <1F40A198-1728-4979-B7D6-4B58EBFC468B>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <1F40A198-1728-4979-B7D6-4B58EBFC468B>.<2>"
), NSLocalizedDescription=The network connection was lost., NSErrorFailingURLStringKey=http://xx.xxx.xx.xxx:xxxxx/api/regs?tel=15071001280&mail=398102832@qq.co&passsalt=59f3062cc5295e1de637d93655067e3f, NSErrorFailingURLKey=http://xx.xxx.xx.xxx:xxxxx/api/regs?tel=15071001280&mail=398102832@qq.co&passsalt=59f3062cc5295e1de637d93655067e3f, _kCFStreamErrorDomainKey=4} [-1005]
FAILURE: Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=-4, NSUnderlyingError=0x280adb690 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x28277d540 [0x1c4949610]>{length = 16, capacity = 16, bytes = 0x10025b2527685ae60000000000000000}, _kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <1F40A198-1728-4979-B7D6-4B58EBFC468B>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <1F40A198-1728-4979-B7D6-4B58EBFC468B>.<2>"
), NSLocalizedDescription=The network connection was lost., NSErrorFailingURLStringKey=http://xx.xxx.xx.xxx:xxxxx/api/regs?tel=15071001280&mail=398102832@qq.co&passsalt=59f3062cc5295e1de637d93655067e3f, NSErrorFailingURLKey=http://xx.xxx.xx.xxx:xxxxx/api/regs?tel=15071001280&mail=398102832@qq.co&passsalt=59f3062cc5295e1de637d93655067e3f, _kCFStreamErrorDomainKey=4}

**Comment by WuYuanhun** [comment]
API not added and default page are not response

**Comment by WuYuanhun** [comment]
please test again. If this bug is removed, just close it. Or inform me anything goes wrong.

**Comment by TonyTang2001** [comment]
The 2nd request now works just fine, but the responseJSON is constantly showing:

SUCCESS: {
    code = 404;
    msg = "not writable";
    status = Error;
}

This "not writable" error shows up **even if the TEL and EMAIL strings do not repeat** the formerly tested values. Please check if the **database connection** is valid.

**Comment by WuYuanhun** [comment]
sooooooooo
😂

**Comment by TonyTang2001** [comment]
OOOOOKKKKKKKay
What is going on...
Please check the response format.

tel=15071001283&mail=398102835@qq.com&passsalt=f3472057638034024829d5854d393c68

FAILURE: responseSerializationFailed(reason: Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed(error: Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))

**Comment by WuYuanhun** [comment]
forget to convert  unicode to binary when transfering
